// Package shim provides functionality for generating the istioctl shim script
// and shell initialization code.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateShimScript creates the istioctl shim script at $ISTIOENV_ROOT/shims/istioctl.
// The shim resolves the correct istioctl version and executes it.
func GenerateShimScript(istioenvRoot string) error {
	shimsDir := filepath.Join(istioenvRoot, "shims")
	if err := os.MkdirAll(shimsDir, 0o755); err != nil {
		return fmt.Errorf("failed to create shims directory: %w", err)
	}

	shimPath := filepath.Join(shimsDir, "istioctl")
	shimContent := fmt.Sprintf(`#!/bin/sh
# This shim is generated by istioctl-env. Do not edit manually.
set -e

ISTIOENV_ROOT="%s"

# Resolve version: ISTIOENV_VERSION > .istioctl-version (walk up) > $ISTIOENV_ROOT/version
resolve_version() {
    # 1. Check ISTIOENV_VERSION env var (shell version)
    if [ -n "$ISTIOENV_VERSION" ]; then
        echo "$ISTIOENV_VERSION"
        return
    fi

    # 2. Walk up directories looking for .istioctl-version (local version)
    local dir="$PWD"
    while true; do
        if [ -f "$dir/.istioctl-version" ]; then
            cat "$dir/.istioctl-version"
            return
        fi
        local parent
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            break
        fi
        dir="$parent"
    done

    # 3. Check global version
    if [ -f "$ISTIOENV_ROOT/version" ]; then
        cat "$ISTIOENV_ROOT/version"
        return
    fi

    echo "istioctl-env: no istioctl version configured" >&2
    echo "Set a version using 'istioctl-env shell', 'istioctl-env local', or 'istioctl-env global'" >&2
    exit 1
}

VERSION="$(resolve_version)"
BINARY="$ISTIOENV_ROOT/versions/$VERSION/istioctl"

if [ ! -x "$BINARY" ]; then
    echo "istioctl-env: version $VERSION is not installed" >&2
    echo "Install it with: istioctl-env install $VERSION" >&2
    exit 1
fi

exec "$BINARY" "$@"
`, istioenvRoot)

	if err := os.WriteFile(shimPath, []byte(shimContent), 0o755); err != nil {
		return fmt.Errorf("failed to write shim script: %w", err)
	}

	return nil
}

// GenerateShellInit returns the shell initialization code that should be
// eval'd in the user's shell (e.g., eval "$(istioctl-env init)").
// It creates a shell function that intercepts the 'shell' subcommand to
// set/unset ISTIOENV_VERSION in the current shell, and prepends the shims
// directory to PATH.
func GenerateShellInit(istioenvRoot string) string {
	return fmt.Sprintf(`export PATH="%s/shims:$PATH"

istioctl-env() {
  if [ "$1" = "shell" ]; then
    if [ -n "$2" ]; then
      # Validate via the real binary first
      command istioctl-env shell "$2" || return $?
      export ISTIOENV_VERSION="$2"
    elif [ "$1" = "shell" ] && [ $# -eq 1 ]; then
      command istioctl-env shell
    fi
  else
    command istioctl-env "$@"
  fi
}
`, istioenvRoot)
}
