// Package shim provides functionality for generating the istioctl shim script
// and shell initialization code.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Supported shell identifiers for shell integration and completion.
const (
	ShellBash = "bash"
	ShellZsh  = "zsh"
	ShellFish = "fish"
)

// SupportedShells lists all shells for which istioctl-env can emit
// shell-integration and completion scripts.
var SupportedShells = []string{ShellBash, ShellZsh, ShellFish}

// GenerateShimScript creates the istioctl shim script at $ISTIOENV_ROOT/shims/istioctl.
// The shim resolves the correct istioctl version and executes it.
//
// The shim is intentionally POSIX (`#!/bin/sh`) and shared by all shells.
func GenerateShimScript(istioenvRoot string) error {
	shimsDir := filepath.Join(istioenvRoot, "shims")
	if err := os.MkdirAll(shimsDir, 0o755); err != nil {
		return fmt.Errorf("failed to create shims directory: %w", err)
	}

	shimPath := filepath.Join(shimsDir, "istioctl")
	shimContent := fmt.Sprintf(`#!/bin/sh
# This shim is generated by istioctl-env. Do not edit manually.
set -e

ISTIOENV_ROOT="%s"

# Resolve the configured version EXPRESSION (which may be an exact pin or a
# SemVer constraint such as ~1.24.0, ^1.24.0, >=1.24.0 <1.26.0, latest,
# or latest-prerelease).
#
# Priority: ISTIOENV_VERSION > .istioctl-version (walk up) > $ISTIOENV_ROOT/version
resolve_version_expr() {
    # 1. Check ISTIOENV_VERSION env var (shell version).
    if [ -n "$ISTIOENV_VERSION" ]; then
        printf '%%s' "$ISTIOENV_VERSION"
        return 0
    fi

    # 2. Walk up directories looking for .istioctl-version (local version).
    dir="$PWD"
    while true; do
        if [ -f "$dir/.istioctl-version" ]; then
            # Command substitution strips trailing newlines; head -n 1 avoids
            # multi-line surprises.  Internal whitespace (e.g. ">=1.24.0 <1.26.0")
            # is preserved.
            head -n 1 "$dir/.istioctl-version"
            return 0
        fi
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            break
        fi
        dir="$parent"
    done

    # 3. Check global version.
    if [ -f "$ISTIOENV_ROOT/version" ]; then
        head -n 1 "$ISTIOENV_ROOT/version"
        return 0
    fi

    return 1
}

VERSION_EXPR="$(resolve_version_expr || true)"
if [ -z "$VERSION_EXPR" ]; then
    echo "istioctl-env: no istioctl version configured" >&2
    echo "Set a version using 'istioctl-env shell', 'istioctl-env local', or 'istioctl-env global'" >&2
    exit 1
fi

# Fast path: the expression is an exact pin and the binary already exists.
# This keeps the common case free of any extra process spawn.
BINARY="$ISTIOENV_ROOT/versions/$VERSION_EXPR/istioctl"
if [ -x "$BINARY" ]; then
    exec "$BINARY" "$@"
fi

# Slow path: either VERSION_EXPR is a constraint, or an exact pin that is
# not installed.  Delegate to the Go binary which understands both and can
# optionally auto-install when ISTIOENV_AUTO_INSTALL=true.
#
# "istioctl-env resolve" prints the concrete version on stdout and sends
# any progress / warning output to stderr, so we can safely capture it.
if ! command -v istioctl-env >/dev/null 2>&1; then
    echo "istioctl-env: cannot resolve $VERSION_EXPR — the istioctl-env binary is not on PATH" >&2
    exit 1
fi

RESOLVED="$(istioctl-env resolve --silent)"
RC=$?
if [ $RC -ne 0 ] || [ -z "$RESOLVED" ]; then
    exit $RC
fi

BINARY="$ISTIOENV_ROOT/versions/$RESOLVED/istioctl"
if [ ! -x "$BINARY" ]; then
    echo "istioctl-env: resolved version $RESOLVED is not installed" >&2
    echo "Install it with: istioctl-env install $RESOLVED" >&2
    echo "Or set ISTIOENV_AUTO_INSTALL=true to install missing versions automatically" >&2
    exit 1
fi

exec "$BINARY" "$@"
`, istioenvRoot)

	if err := os.WriteFile(shimPath, []byte(shimContent), 0o755); err != nil {
		return fmt.Errorf("failed to write shim script: %w", err)
	}

	return nil
}

// DetectShell inspects $SHELL and returns a supported shell identifier
// ("bash", "zsh", or "fish"). If $SHELL is unset or does not match one of the
// supported shells, DetectShell returns the empty string so callers can decide
// how to warn the user and fall back.
func DetectShell() string {
	sh := strings.TrimSpace(os.Getenv("SHELL"))
	if sh == "" {
		return ""
	}
	base := filepath.Base(sh)
	switch base {
	case ShellBash, ShellZsh, ShellFish:
		return base
	}
	return ""
}

// NormalizeShell validates an explicit --shell value and returns the
// canonical identifier. It returns an error that lists the valid choices if
// the value is empty or unrecognized.
func NormalizeShell(shell string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(shell)) {
	case ShellBash:
		return ShellBash, nil
	case ShellZsh:
		return ShellZsh, nil
	case ShellFish:
		return ShellFish, nil
	default:
		return "", fmt.Errorf("unknown shell %q: valid choices are %s", shell, strings.Join(SupportedShells, ", "))
	}
}

// GenerateShellInit returns the shell initialization code for the requested
// shell. It is a thin wrapper around the per-shell generators. Unknown or
// empty shell values fall back to bash so this helper never panics.
func GenerateShellInit(istioenvRoot, shell string) string {
	switch strings.ToLower(strings.TrimSpace(shell)) {
	case ShellZsh:
		return GenerateShellInitZsh(istioenvRoot)
	case ShellFish:
		return GenerateShellInitFish(istioenvRoot)
	default:
		return GenerateShellInitBash(istioenvRoot)
	}
}

// GenerateShellInitBash returns the bash shell initialization code that
// should be eval'd (e.g., eval "$(istioctl-env init)"). It creates a shell
// function that intercepts the 'shell' subcommand to set/unset
// ISTIOENV_VERSION in the current shell, and prepends the shims directory to
// PATH.
func GenerateShellInitBash(istioenvRoot string) string {
	return fmt.Sprintf(`export PATH="%s/shims:$PATH"

istioctl-env() {
  if [ "$1" = "shell" ]; then
    if [ "$2" = "-h" ] || [ "$2" = "--help" ]; then
      command istioctl-env shell "$2"
    elif [ -n "$2" ]; then
      # Validate via the real binary first
      command istioctl-env shell "$2" || return $?
      export ISTIOENV_VERSION="$2"
    elif [ "$1" = "shell" ] && [ $# -eq 1 ]; then
      command istioctl-env shell
    fi
  else
    command istioctl-env "$@"
  fi
}
`, istioenvRoot)
}

// GenerateShellInitZsh returns the zsh shell initialization code. Semantics
// match the bash version; the body is wrapped in `function istioctl-env() {}`
// which is valid in both shells but keeps the two generators independent so
// zsh-only tweaks can land without disturbing bash users.
func GenerateShellInitZsh(istioenvRoot string) string {
	return fmt.Sprintf(`export PATH="%s/shims:$PATH"

function istioctl-env() {
  if [ "$1" = "shell" ]; then
    if [ "$2" = "-h" ] || [ "$2" = "--help" ]; then
      command istioctl-env shell "$2"
    elif [ -n "$2" ]; then
      # Validate via the real binary first
      command istioctl-env shell "$2" || return $?
      export ISTIOENV_VERSION="$2"
    elif [ "$1" = "shell" ] && [ $# -eq 1 ]; then
      command istioctl-env shell
    fi
  else
    command istioctl-env "$@"
  fi
}
`, istioenvRoot)
}

// GenerateShellInitFish returns the fish shell initialization code. Fish uses
// different quoting, variable, and function syntax than bash/zsh, so it is
// implemented separately. It should be sourced via
// `istioctl-env init --shell fish | source`.
func GenerateShellInitFish(istioenvRoot string) string {
	return fmt.Sprintf(`set -gx PATH "%s/shims" $PATH

function istioctl-env
    if test "$argv[1]" = "shell"; and contains -- "$argv[2]" -h --help
        command istioctl-env shell $argv[2]
    else if test "$argv[1]" = "shell"; and test (count $argv) -gt 1
        command istioctl-env shell $argv[2]; or return $status
        set -gx ISTIOENV_VERSION $argv[2]
    else if test "$argv[1]" = "shell"
        command istioctl-env shell
    else
        command istioctl-env $argv
    end
end
`, istioenvRoot)
}
